### PR TITLE
fix(autoclose): fix popup automatic closing on touch on iOS

### LINKED ISSUE #2995: Dropdown does not autoClose on outside click (iOS only)
### Bug description:

Dropdown does not autoClose on outside click (iOS only). Tested with an iPad Air 2, iOS 12.1.2.

### Link to minimally-working StackBlitz that reproduces the issue:

With your iOS device, visit
https://ng-bootstrap.github.io/#/components/dropdown/examples
Open the first Dropdown example and click outside of it. The Dropdown will not close.

### Versions of Angular, ng-bootstrap and Bootstrap:

See https://ng-bootstrap.github.io

### PR DESCRIPTION
**Pull request by maxokorokov**
Tested on Android, Windows 10 with touch and iOS.

Autoclose was broken only on iOS, other browsers work fine with `mousedown/mouseup` while `iOS` needs to have `touchstart/touchend`

Fixes #2995

cc @divdavem

### CODE REVIEW

File: src/util/autoclose.ts [hunk 1]
```diff
@@ -39,18 +45,18 @@ export class AutoClose {
...
+                                .pipe(map(shouldCloseOnClick), takeUntil(closed$));
 
-        const outsideClicks$ = fromEvent<MouseEvent>(this._document, 'mouseup')
-                                   .pipe(
-                                       withLatestFrom(mouseDowns$), filter(([_, shouldClose]) => shouldClose), delay(0),
-                                       takeUntil(closed$));
+        const closeableClicks$ = fromEvent<MouseEvent>(this._document, iOS ? 'touchend' : 'mouseup')
+                                     .pipe(
+                                         withLatestFrom(mouseDowns$), filter(([_, shouldClose]) => shouldClose),
+                                         delay(iOS ? 16 : 0), takeUntil(closed$));
```
Comment (maxokorokov) [inline src/util/autoclose.ts]: If anybody has a better solution for this, please share it :)

Problem is when there is a `click` handler on a triggering element (say, button): 
- to open: `click` → `open()` 
- to close: `touchdown` → `touchup` → `click (is still generated that leads to)` → `open() (popup reopening)`

by delaying the `touchup`, `click` and `open()` are processed while the popup is still open

**Comment by maxokorokov** [comment]
As discussed, I'll merge the fix as-is and we'll investigate better ways for handling focus and closing things

cc @fbasso @benouat
