### PR TITLE
fix(modal): prevent modal from closing when using scrollbar

### LINKED ISSUE #3518: Modals dismissed by mouse release when trying to scroll the window
### Bug description:
When you try to scroll the modal window by clicking and dragging the scrollbar, the modal gets dismissed on mouse release. The following should clarify the issue:

chrome-capture (21)

### Link to minimally-working StackBlitz that reproduces the issue:
[here the example](https://ng-bootstrap.github.io/stackblitzes/modal/basic/stackblitz.html)

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 8.2.13

ng-bootstrap: 5.1.4

Bootstrap: 4.3.1

### PR DESCRIPTION
**Pull request by maxokorokov**
Have to use `mousedown` - `mouseup` - `click` to handle closing correctly:
- using `click` fixes the #3518
- using `mousedown` - `mouseup` fixes closing on accidental drags from modal dialog → backdrop

Fixes #3518

### CODE REVIEW

File: src/modal/modal-window.ts [hunk 1]
```diff
@@ -40,6 +41,9 @@ import {ModalDismissReasons} from './modal-dismiss-reasons';
 export class NgbModalWindow implements OnInit,
     AfterViewInit, OnDestroy {
   private _elWithFocus: Element;  // element that is focused prior to modal opening
+  private _preventClose = false;
```
Comment (peterblazejewicz) [inline src/modal/modal-window.ts]: This works well if used as locally scoped var:
```ts
this._zone.runOutsideAngular(() => {
      let _preventClose = false;
...
```

File: src/modal/modal-window.ts [hunk 2]
```diff
@@ -52,40 +56,51 @@ export class NgbModalWindow implements OnInit,
...
+                  fromEvent<MouseEvent>(nativeElement, 'mouseup')
+                      .pipe(takeUntil(this.dismissEvent), take(1))
+                      .subscribe(({target}) => { this._preventClose = nativeElement === target; });
+                }))
+          .subscribe();
 
-      fromEvent<MouseEvent>(this._elRef.nativeElement, 'mouseup')
-          .pipe(takeUntil(this.dismissEvent), withLatestFrom(mouseDowns$), filter(([_, shouldClose]) => shouldClose))
-          .subscribe(() => this._zone.run(() => this.dismiss(ModalDismissReasons.BACKDROP_CLICK)));
+      // We have to use 'click' event to prevent modal from closing when the modal is too big and we have a scrollbar
```
Comment (peterblazejewicz) [inline src/modal/modal-window.ts]: I think current wording can be misleading, as the 'click' is the primary way to dismis modal via backdrop, mosue down/up is used to prevent accidental close when released from 'down > drag > release' action when fired 'click' closes dialog.

File: src/modal/modal-window.ts (hunk 1 above)
Comment (maxokorokov) [reply src/modal/modal-window.ts]: Good idea, will fix that

File: src/modal/modal-window.ts (hunk 2 above)
Comment (maxokorokov) [reply src/modal/modal-window.ts]: Thanks, apparently was thinking about the issue when writing this :) Will update comments

File: src/modal/modal-window.ts [hunk 3]
```diff
@@ -52,40 +55,56 @@ export class NgbModalWindow implements OnInit,
...
+      // inside the modal dialog and releasing it outside
+      let preventClose = false;
+      fromEvent<MouseEvent>(this._dialogEl.nativeElement, 'mousedown')
+          .pipe(takeUntil(this.dismissEvent), tap(() => {
+                  preventClose = false;
+                  fromEvent<MouseEvent>(nativeElement, 'mouseup')
+                      .pipe(takeUntil(this.dismissEvent), take(1))
+                      .subscribe(({target}) => { preventClose = nativeElement === target; });
+                }))
+          .subscribe();
```
Comment (benouat) [inline src/modal/modal-window.ts]: I think we could safely rewrite this part as

```typescript
.pipe(
  takeUntil(this.dismissEvent),
  tap(() => { preventClose = false; }),
  switchMap(() => fromEvent<MouseEvent>(nativeElement, 'mouseup')
    .pipe(takeUntil(this.dismissEvent), take(1))
  )
).subscribe(({target}) => { preventClose = nativeElement === target; });
```

Comment (maxokorokov) [reply src/modal/modal-window.ts]: Done. Thanks, this looks much better!

```ts
      fromEvent<MouseEvent>(this._dialogEl.nativeElement, 'mousedown')
          .pipe(
              takeUntil(this.dismissEvent), 
              tap(() => preventClose = false),
              switchMap(() => fromEvent<MouseEvent>(nativeElement, 'mouseup').pipe(takeUntil(this.dismissEvent), take(1))),
              filter(({target}) => nativeElement === target))
          .subscribe(() => { preventClose = true; });
```

**Comment by benouat** [comment]
@maxokorokov when CI is ok, let's merge it 🚀
