### PR TITLE
fix(focustrap): discarding tabindex='-1' when finding element

### LINKED ISSUE #2884: Modal: Elements with tabindex="-1" get focused
When opening a modal, the documentation says the first focusable element is focused (if there is no ngbAutofocus marker). But when I assign `tabindex="-1"` to the first focusable element, it is still focused.

Link to StackBlitz reproduction: [https://stackblitz.com/edit/angular-aoqoet](https://stackblitz.com/edit/angular-aoqoet)
The expection here is, that instead of the close button, the date field gets focused. But if you check with `document.activeElement`, the close button is still focused

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 6.1.9

ng-bootstrap: 3.3.0, but is not yet fixed in master branch

Bootstrap: 4.1.3

I inspected the code and found the place, where the bug occurs:
File: src/util/focus-trap.ts
Line: 6-9

Today it is
`const FOCUSABLE_ELEMENTS_SELECTOR = [
  'a[href]', 'button:not([disabled])', 'input:not([disabled]):not([type="hidden"])', 'select:not([disabled])',
  'textarea:not([disabled])', '[contenteditable]', '[tabindex]:not([tabindex="-1"])'
].join(', ');`

should be like this (note the `:not([tabindex="-1"])`) after each selector

`var FOCUSABLE_ELEMENTS_SELECTOR = [
    'a[href]:not([tabindex="-1"])', 'button:not([disabled]):not([tabindex="-1"])', 'input:not([disabled]):not([type="hidden"]):not([tabindex="-1"])', 'select:not([disabled]):not([tabindex="-1"])',
    'textarea:not([disabled]):not([tabindex="-1"])', '[contenteditable]:not([tabindex="-1"])', '[tabindex]:not([tabindex="-1"])'
].join(', ');`

### PR DESCRIPTION
**Pull request by benouat**
When focus-trap needs to figure out what are the boundaries elements (first and last focusable elements) we need to perform an extra check to filter out elements with `tabindex="-1"`

Closes #2884

### CODE REVIEW

File: src/modal/modal.spec.ts [hunk 1]
```diff
@@ -882,6 +893,16 @@ export class WithAutofocusModalCmpt {
...
 }
 
+@Component({
+  selector: 'modal-skip-tabindex-firstfocusable-cmpt',
+  template: `
+  <button tabindex="-1" class="firstFocusable close">Close</button>
+  <button class="other">Other button</button>
+`
+})
+export class WithSkipTabindexFirstFocusableModalCmpt {
```
Comment (maxokorokov) [inline src/modal/modal.spec.ts]: Good naming! Though, could you change to `WithNegativeTabIndexElementThatShouldBeSkippedWhileFindingFirstFocusableElementModalComponent`? 

Just kidding :)
