### PR TITLE
fix(modal): don't close modal on ESC if file dialog is open

### LINKED ISSUE #3439: Modal is dismissed with Esc when file dialog is open
### Bug description:
1) Open a modal with file input 
2) Click Browse on file input - file dialog is open
3) Dismiss file dialog with Esc => both file dialog (correct) and modal are dismissed (wrong)

### Link to minimally-working StackBlitz that reproduces the issue:
https://stackblitz.com/edit/angular-tfz1e2?file=app/modal-basic.ts

Open a modal, click file dialog, hit Esc and observe wrong behavior.

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular:
v8.2.4

ng-bootstrap:
v5.1.2

Bootstrap:
v4.3

### PR DESCRIPTION
**Pull request by maxokorokov**
Keyboard events in modal and autoclose handling use 'keydown' instead of 'keyup'

Fixes #3439 

---

Unfortunately no way of adding e2e tests for this case

### CODE REVIEW

File: src/util/autoclose.ts [hunk 1]
```diff
@@ -39,7 +39,7 @@ export function ngbAutoClose(
         }
       };
 
-      const escapes$ = fromEvent<KeyboardEvent>(document, 'keyup')
+      const escapes$ = fromEvent<KeyboardEvent>(document, 'keydown')
```
Comment (peterblazejewicz) [inline src/util/autoclose.ts]: This one aligns with the modal `<dialog>` closing with ESC
👍

**Comment by peterblazejewicz** [comment]
for reference #3415:  same behaviour with this change (local tests, Catalina)
