### PR TITLE
fix(position): wrong placement class applies in some cases

### LINKED ISSUE #3040: Popover arrow placement can be incorrect when multiple placements are used
### Bug description:

When using multiple `Placement` values to position a popover, if none of them result in the popover being on screen, the first `Placement` is used to position the popover, but the _last_ `Placement` is used to control where the popovers arrow appears.

image

### Link to minimally-working StackBlitz that reproduces the issue:

https://stackblitz.com/edit/angular-ducwpd

Click on the button to open the popover. The popover will appear centered over the button, but the arrow will be to the right edge of the popover. 

If you change the `placement` order in `app.component.html` to `['top', 'top-right', 'top-left']`, the arrow will appear towards the left edge of the popover. If you change the placements to just contain `top`, the arrow is centered as you would expect.

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 7.2.6

ng-bootstrap: 4.0.4

Bootstrap: 4.3.1

### PR DESCRIPTION
**Pull request by fbasso**
fix #3040

### CODE REVIEW

File: src/util/positioning.ts [hunk 1]
```diff
@@ -235,7 +235,7 @@ export function positionElements(
     }
 
     // Remove the baseClasses for further calculation, except for the last one
```
Comment (benouat) [inline src/util/positioning.ts]: You should also adapt the comment here to get rid of _execpt for the last one_

**Comment by fbasso** [comment]
Changes done :)
