### PR TITLE
Fix accordion hydration + onpush

### LINKED ISSUE #4758: Accordion: destroyOnHide is not respected and component content is present in the DOM with OnPush strategy
### Bug description:
When `destroyOnHide` is set to `true` or not (which according documentation is `true` by default), after collapsing accordion, the body (NgbAccordionBody) still contains its content a.k.a none of the elements are removed from the DOM. I've experience this issue with `OnPush` change detection strategy. I decide to fork and clone the repo, then work it out and found that regardless of which change detection strategy I have choose, DEMO components still present their content of the body, when accordion is collapsed. I have experience this problem with v.16 then decide to clone and test the latest 17, issue is still present.

### Link to minimally-working StackBlitz that reproduces the issue:
Fork/clone the project -> go to : `demo/src/app/components/accordion/demos/basic/accordion-basic.ts` and change the strategy to `OnPush` -> yarn demo -> navigate to : components/accordion/examples -> inspect first basic example and its DOM content while expand/collapse the accordion.
Expecting result: DOM elements/content from body (NgbAccordionBody) to be remove from the DOM, once its collapsed.
Actual result: DOM elements/content of the body are present in the DOM, when accordion is collapsed.

I woud like to provide fix for this issue.

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 17, 18

ng-bootstrap: 16,17

Bootstrap:5.3.*

### LINKED ISSUE #4771: Accordion collapse/expand not working when SSR is enabled
### Bug description:
When creating an Angular 18 project with SSR enables the accordion collapse and expand does not work.
When the page loads the following Javascript error is thrown in the console:

_ERROR Error: Expecting instance of DOM Element
    at assertDomElement (chunk-POGNINR2.js?v=047c9d3c:9917:11)
    at getComponent$1 (chunk-POGNINR2.js?v=047c9d3c:9755:16)
    at markRNodeAsHavingHydrationMismatch (chunk-POGNINR2.js?v=047c9d3c:10207:19)
    at validateSiblingNodeExists (chunk-POGNINR2.js?v=047c9d3c:13408:5)
    at siblingAfter (chunk-POGNINR2.js?v=047c9d3c:13865:18)
    at locateDehydratedViewsInContainer (chunk-POGNINR2.js?v=047c9d3c:14388:24)
    at populateDehydratedViewsInLContainerImpl (chunk-POGNINR2.js?v=047c9d3c:15282:42)
    at locateOrCreateAnchorNode (chunk-POGNINR2.js?v=047c9d3c:15292:8)
    at createContainerRef (chunk-POGNINR2.js?v=047c9d3c:15242:3)
    at injectViewContainerRef (chunk-POGNINR2.js?v=047c9d3c:15064:10)_

### Link to minimally-working StackBlitz that reproduces the issue:
https://stackblitz.com/~/github.com/WayneKruger/ng-boorstrap-ssr

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 18.2.8 (but same happens in any v18)

ng-bootstrap: 17.0.1

Bootstrap: 5.3.3 (Same happens in 5.3.2)

I did not test any other major versions.

### PR DESCRIPTION
**Pull request by quentinderoubaix**
Before submitting a pull request, please make sure you have at least performed the following:

 - [x] read and followed the [CONTRIBUTING.md](https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CONTRIBUTING.md) and [DEVELOPER.md](https://github.com/ng-bootstrap/ng-bootstrap/blob/master/DEVELOPER.md) guide.
 - [x] built and tested the changes locally.
 - [x] added/updated any applicable tests.
 - [x] added/updated any applicable API documentation.
 - [x] added/updated any applicable demos.

Fixes #4758
Fixes #4771

### CODE REVIEW

File: src/accordion/accordion.directive.ts [hunk 1]
```diff
@@ -32,20 +33,22 @@ let nextId = 0;
  *
  * @since 14.1.0
  */
-@Directive({
+@Component({
```
Comment (maxokorokov) [inline src/accordion/accordion.directive.ts:36]: This reverts #4502

Comment (quentinderoubaix) [reply src/accordion/accordion.directive.ts:37]: Indeed !
I have added a public `elementRef` reference in order to help retrieve the native element with template variables.

File: src/accordion/accordion.directive.ts [hunk 2]
```diff
@@ -32,20 +34,24 @@ let nextId = 0;
...
 	},
 })
 export class NgbAccordionBody implements AfterContentChecked, OnDestroy {
-	private _vcr = inject(ViewContainerRef);
-	private _element = inject(ElementRef<HTMLElement>).nativeElement;
 	private _item = inject(NgbAccordionItem);
-
 	private _viewRef: EmbeddedViewRef<any> | null = null;
 
+	public readonly elementRef = inject(ElementRef);
```
Comment (maxokorokov) [inline src/accordion/accordion.directive.ts:52]: just don't forget to put the comment with `@since x.x.x` annotation when doing a release, so it would be documented and visible in API documentation

**Review by maxokorokov — APPROVED** [review]
LGTM, thanks!
