### PR TITLE
fix(typeahead): input value properly reset when hint/ngModel are used together

### LINKED ISSUE #2816: it is not possible to reset input value for typeahead component
### Bug description:

For the typeahead component, it is not possible to clear the model after the results list appears. If the results list doesn't appear, the model can be cleared from a button without problem

### Steps to reproduce:
- open [https://stackblitz.com/edit/angular-rybwwn-w3w4ca](https://stackblitz.com/edit/angular-rybwwn-w3w4ca)
- introduce text "aaa"
- click on button "Clear"
- the input is cleared
- introduce text "ala"
- click on button "Clear"
- the input is not cleared

You can fork a StackBlitz from one of our [demos](https://ng-bootstrap.github.io/#/components) and use it as a starting point.

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 6.1.0

ng-bootstrap: 3.3.0

Bootstrap: 4.0

### PR DESCRIPTION
**Pull request by benouat**
I refactored a bit (very very little bit) the way `showHint` and especially how to backup and restore input value properly when:

+ model gets reset
+ window is dismissed (Esc)
+ window is dismissed (click outside)

fixes #2816
closes #2850 (this PR closes and replaces that one)

PS: on the long run `showHint` would probably need a complete overhaul

### CODE REVIEW

File: src/typeahead/typeahead.ts [hunk 1]
```diff
@@ -206,7 +209,12 @@ export class NgbTypeahead implements ControlValueAccessor,
 
   registerOnTouched(fn: () => any): void { this._onTouched = fn; }
 
-  writeValue(value) { this._writeInputValue(this._formatItemForInput(value)); }
+  writeValue(value) {
+    this._writeInputValue(this._formatItemForInput(value));
+    if (this.showHint) {
```
Comment (maxokorokov) [inline src/typeahead/typeahead.ts]: I don't think it is necessary, because the first thing you do on user input is already `this._inputValueBackup = value;`

Comment (benouat) [reply src/typeahead/typeahead.ts]: I removed it.
