### PR TITLE
fix(carousel): change sildes on prev/next/select API calls with OnPush

### LINKED ISSUE #2766: Bug in Carousel for external Previous/Next buttons
### Bug description:

Steps to reproduce:

1. Click "Next" button - observe nothing happens.
2. Move your mouse into the image - observe the Carousel advance on mouseenter.

Other Notes:

* If you click the Next button twice, then mouseenter the image, it will advance 2 images (corresponding exactly to number of clicks). It's correctly keeping track of active slide, but not advancing until mouse enter.
* Same behavior (in reverse) for Previous button.

### Link to minimally-working StackBlitz that reproduces the issue:

StackBlitz sample that reproduces issue:  https://stackblitz.com/edit/ng-bootstrap-carousel-bug

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 6.1.0

ng-bootstrap: 3.3.0

Bootstrap:

### PR DESCRIPTION
**Pull request by maxokorokov**
Regression introduced after marking carousel OnPush due to lack of tests. Now calling `detectChanges()` on interval and all public API actions.

Fixes #2766

### CODE REVIEW

File: src/carousel/carousel.ts [hunk 1]
```diff
@@ -202,6 +199,9 @@ export class NgbCarousel implements AfterContentChecked,
       this._start$.next();
       this.activeId = selectedSlide.id;
     }
+
+    // we get here after the interval fires or any external API call like next(), prev() or select()
+    this._cd.detectChanges();
```
Comment (pkozlowski-opensource) [inline src/carousel/carousel.ts]: Shouldn't this be `markForCheck`? What would happen in a scenario where click on prev / next is calling prev / next on a carousel _and_ is adding a new slide (ex. from `ngFor`). Would the content of a carousel be checked if we just call detect changes on the carousel itself?

Comment (pkozlowski-opensource) [reply src/carousel/carousel.ts]: > markForCheck would only refresh it on next CD, isn't it correct ?

I would say: in the current CD (the one that would be run at the end of JS loop, before any rendering is done). So I believe that this is the behaviour we actually want.

We should add a test for the above scenario to be sure.

**Comment by maxokorokov** [comment]
@pkozlowski-opensource, sure shouldn't run CD synchronously right away, will change to `markForCheck`

Actually you're right, you're example won't work with `detectChanges`, didn't get it at first. Added a test for it

**Comment by pkozlowski-opensource** [comment]
LGTM. Feel free to merge when CI gets green.
