### PR TITLE
fix(dropdown): close dropdown menu on Enter / Space

### LINKED ISSUE #3142: Dropdown menu isn't closed on Enter / Space
### Bug description:

Dropdown should be closed when pressing <kbd>Enter</kbd> / <kbd>Space</kbd> and dropdown item is focused, but it's not

### Link to minimally-working StackBlitz that reproduces the issue:

Stackblitz with both ng-bootstrap and bootstrap dropdowns to compare:

https://stackblitz.com/edit/angular-uahpzh?file=index.html

To reproduce:
- Focus `ng-bootstrap` button with keyboard
- Press <kbd>ArrowDown</kbd> to open menu
- Press <kbd>ArrowDown</kbd> again to focus first item ('New around here? Signup')
- Press <kbd>Enter</kbd> / <kbd>Space</kbd>
- Dropdown menu should close, but it's not.

### Versions of Angular, ng-bootstrap and Bootstrap:

ng-bootstrap: 4.1.1

### PR DESCRIPTION
**Pull request by maxokorokov**
Fixes #3142

### CODE REVIEW

File: src/dropdown/dropdown.ts [hunk 1]
```diff
@@ -57,7 +57,9 @@ export class NgbDropdownItem {
     '(keydown.ArrowUp)': 'dropdown.onKeyDown($event)',
     '(keydown.ArrowDown)': 'dropdown.onKeyDown($event)',
     '(keydown.Home)': 'dropdown.onKeyDown($event)',
-    '(keydown.End)': 'dropdown.onKeyDown($event)'
+    '(keydown.End)': 'dropdown.onKeyDown($event)',
+    '(keydown.Enter)': 'dropdown.onKeyDown($event)',
+    '(keydown.Space)': 'dropdown.onKeyDown($event)'
```
Comment (benouat) [inline src/dropdown/dropdown.ts]: I think it's time to keep a single `(keydown)` binding and create a `switch` or `[]. includes` in a local `onKeyDown($event)` that will delegate to `dropdown.onKeyDown($event)`

WDYT ?

Comment (maxokorokov) [reply src/dropdown/dropdown.ts]: @benouat, I agreed and I have a refactoring of keyboard handling in works. Would ideally just keep it separate from this PR

- you'll see a comment by @fbasso soon, but actually `NgbDropdownToggle` doesn't need `(keydown.Enter|Space)` handlers at all. I'll fix that in a bit.
- I'll split the `onKeyDown` into two functions for `NgbDropdownToggle` and `NgbDropdownMenu` I guess and it should simplify things.

P.S. also `[].includes` needs a polyfill :)

**Comment by maxokorokov** [comment]
@fbasso thanks for the review:
- removed unnecessary handlers
- added tests for `Enter/Space` inside the form
