### PR TITLE
fix(dropdown): allow template directive on the menu

### LINKED ISSUE #3246: Can't use a template directive as a dropdown menu
### Bug description:

When using a template directive on a ngbDropdownMenu, the menu is not placed correctly on first click. When clicking again, the menu is at the right place.

This is due to the fact that `offsetParent` is looking for a parent with a position attribute. This is normally solved by `_applyPlacementClasses` in `dropdown.ts` with the `dropdown` class. 

If you try to add a template to it, ngOnInit is called before the full template rendering. This causes  `NgbDropdown._menu` to be null and `dropdown` class is never applied.

A possible solution (not tested) could be ngAfterViewInit()

### Link to minimally-working StackBlitz that reproduces the issue:

https://stackblitz.com/edit/problem-template-dropdown

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 7

ng-bootstrap: 4.2.1

Bootstrap: 4

### PR DESCRIPTION
**Pull request by fbasso**
fix #3246

### CODE REVIEW

File: src/dropdown/dropdown.ts [hunk 1]
```diff
@@ -240,9 +242,10 @@ export class NgbDropdown implements OnInit, OnDestroy {
   }
 
   private _setCloseHandlers() {
+    const anchor = this._anchor;
     ngbAutoClose(
         this._ngZone, this._document, this.autoClose, () => this.close(), this._closed$,
-        this._menu ? [this._menuElement.nativeElement] : [], this._anchor ? [this._anchor.getNativeElement()] : [],
+        this._menu ? [this._menuElement.nativeElement] : [], anchor ? [anchor.getNativeElement()] : [],
```
Comment (benouat) [inline src/dropdown/dropdown.ts]: This refactor is not strictly related to the underlying issue.

File: src/dropdown/dropdown.ts [hunk 2]
```diff
@@ -341,14 +344,16 @@ export class NgbDropdown implements OnInit, OnDestroy {
   }
 
   private _getMenuElements(): HTMLElement[] {
-    if (this._menu == null) {
+    const menu = this._menu;
```
Comment (benouat) [inline src/dropdown/dropdown.ts]: Same here

File: src/dropdown/dropdown.ts [hunk 3]
```diff
@@ -341,14 +344,16 @@ export class NgbDropdown implements OnInit, OnDestroy {
...
+    if (menu == null) {
       return [];
     }
-    return this._menu.menuItems.filter(item => !item.disabled).map(item => item.elementRef.nativeElement);
+    return menu.menuItems.filter(item => !item.disabled).map(item => item.elementRef.nativeElement);
   }
 
   private _positionMenu() {
-    if (this.isOpen() && this._menu) {
+    const menu = this._menu;
```
Comment (benouat) [inline src/dropdown/dropdown.ts]: Same here

File: src/dropdown/dropdown.ts [hunk 4]
```diff
@@ -364,9 +369,10 @@ export class NgbDropdown implements OnInit, OnDestroy {
 
   private _resetContainer() {
     const renderer = this._renderer;
-    if (this._menuElement) {
+    const menuElement = this._menuElement;
```
Comment (benouat) [inline src/dropdown/dropdown.ts]: Same here.

File: src/dropdown/dropdown.ts [hunk 5]
```diff
@@ -396,7 +402,8 @@ export class NgbDropdown implements OnInit, OnDestroy {
   }
 
   private _applyPlacementClasses(placement?: Placement) {
-    if (this._menu) {
+    const menu = this._menu;
```
Comment (benouat) [inline src/dropdown/dropdown.ts]: Same here.

**Comment by benouat** [comment]
@fbasso could you please rebase ?
